"""greenhouse_token

Revision ID: 4d6a4c11c732
Revises: 3d81f17e9d94
Create Date: 2023-05-05 07:25:37.724061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6a4c11c732'
down_revision = '3d81f17e9d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greenhouse', sa.Column('token_hash', sa.String(), nullable=True))
    op.execute("UPDATE greenhouse SET token_hash='nothing'")
    op.alter_column('greenhouse', 'token_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greenhouse', 'token_hash')
    # ### end Alembic commands ###
