"""added status

Revision ID: 5a5c0c55c0a9
Revises: b3f4b12da61d
Create Date: 2022-10-20 07:09:38.075995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5c0c55c0a9'
down_revision = 'b3f4b12da61d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greenhouse_state', sa.Column('ipm_status_next_time', sa.DateTime(), nullable=True))
    op.add_column('greenhouse_state', sa.Column('lighting_status_dli', sa.Float(), nullable=True))
    op.add_column('greenhouse_state', sa.Column('irrigation_status_next_time', sa.DateTime(), nullable=True))
    op.add_column('greenhouse_state', sa.Column('irrigation_status_next_zone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greenhouse_state', 'irrigation_status_next_zone')
    op.drop_column('greenhouse_state', 'irrigation_status_next_time')
    op.drop_column('greenhouse_state', 'lighting_status_dli')
    op.drop_column('greenhouse_state', 'ipm_status_next_time')
    # ### end Alembic commands ###
