"""irrigation zone index

Revision ID: 9f40302a8718
Revises: 5a5c0c55c0a9
Create Date: 2022-10-27 07:02:54.094651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f40302a8718'
down_revision = '5a5c0c55c0a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greenhouse_state_irrigation', sa.Column('index', sa.Integer(), nullable=True))
    op.execute("UPDATE greenhouse_state_irrigation SET index=0")
    op.alter_column('greenhouse_state_irrigation', 'index', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greenhouse_state_irrigation', 'index')
    # ### end Alembic commands ###
