"""added zone names

Revision ID: b3f4b12da61d
Revises: 458e919b974d
Create Date: 2022-10-19 22:39:00.333718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f4b12da61d'
down_revision = '458e919b974d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greenhouse_state_irrigation', sa.Column('recipe_name', sa.String(), nullable=True))
    op.execute("UPDATE greenhouse_state_irrigation SET recipe_name=''")
    op.alter_column('greenhouse_state_irrigation', 'recipe_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greenhouse_state_irrigation', 'recipe_name')
    # ### end Alembic commands ###
