"""restart

Revision ID: d0f08d126143
Revises: 
Create Date: 2022-08-25 21:18:02.548733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0f08d126143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouse',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('type', sa.Enum('proto_1_ithaca', name='greenhousetype'), nullable=False),
        sa.Column('location_name', sa.String(), nullable=False),
        sa.Column('longitude', sa.Integer(), nullable=False),
        sa.Column('latitude', sa.Integer(), nullable=False),
        sa.Column('timezone', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('units', sa.Enum('metric', 'imperial', name='units'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('greenhouse_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('greenhouse_id', sa.Integer(), nullable=False),
        sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('temperature', sa.Integer(), nullable=False),
        sa.Column('humidity', sa.Float(), nullable=False),
        sa.Column('quantum', sa.Float(), nullable=False),
        sa.Column('environment_mode', sa.Enum('automatic', 'manual', name='controlmode'), nullable=False),
        sa.Column('environment_state', sa.Enum('default', name='environmentstate'), nullable=False),
        sa.Column('ipm_mode', sa.Enum('automatic', 'manual', name='controlmode'), nullable=False),
        sa.Column('ipm_state', sa.Enum('default', name='ipmstate'), nullable=False),
        sa.Column('lighting_mode', sa.Enum('automatic', 'manual', name='controlmode'), nullable=False),
        sa.Column('lighting_state', sa.Enum('default', name='lightningstate'), nullable=False),
        sa.Column('irrigation_mode', sa.Enum('automatic', 'manual', name='controlmode'), nullable=False),
        sa.Column('irrigation_state', sa.Enum('default', name='irrigationstate'), nullable=False),
        sa.Column('heater', sa.Boolean(), nullable=False),
        sa.Column('exhaust', sa.Boolean(), nullable=False),
        sa.Column('ventilator', sa.Boolean(), nullable=False),
        sa.Column('sulfur', sa.Boolean(), nullable=False),
        sa.Column('lights', sa.Boolean(), nullable=False),
        sa.Column('valves', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('weather_temperature', sa.Integer(), nullable=True),
        sa.Column('weather_humidity', sa.Float(), nullable=True),
        sa.Column('weather_sky', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_greenhouse_state_time'), 'greenhouse_state', ['time'], unique=False)
    op.create_table('user_greenhouse',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('greenhouse_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_greenhouse')
    op.drop_index(op.f('ix_greenhouse_state_time'), table_name='greenhouse_state')
    op.drop_table('greenhouse_state')
    op.drop_table('user')
    op.drop_table('greenhouse')
    # ### end Alembic commands ###
